---
title: "Catch'em all"
author: "Leonardo Martins"
date: "24 de julho de 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Disseminating the code

```{r}
#Breeding Reports Like Crazy
library(rmarkdown)
require(dplyr)
```

```{r}
#It only works in Unix (Linux or OSX) - Using Stream Editor from Bash
x<-"sed -e 's/full_no_zero/x2/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/x2_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var0/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var0_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var1/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var1_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var2/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var2_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var3/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var3_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var4/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var4_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var5/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var5_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var6/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var6_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var7/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var7_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var8/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var8_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var9/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var9_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var10/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var10_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var11/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var11_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var12/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var12_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var13/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var13_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var14/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var14_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var15/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var15_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var16/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var16_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var17/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var17_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var18/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var18_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var19/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var19_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var20/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var20_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var21/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var21_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var22/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var22_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var23/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var23_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/var24/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/var24_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/atividade/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/atividade_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/acesso/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/acesso_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/acesso_positivo/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/acesso_positivo_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/acesso_negativo/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/acesso_negativo_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/confianca/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/confianca_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/acessoeconfianca/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/acessoeconfianca_0_interactive.Rmd" %>% system()

x<-"sed -e 's/full_no_zero/total/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd > ~/SNArRDJF/Analises/0/total_0_interactive.Rmd" %>% system()
```

#Breeding Fancy Names Reports Like Crazy
```{r}
x<-"sed -e 's/fuull_no_zero_fancy/1.1 - REDE COMPLETA (full_no_zero)/g' ~/SNArRDJF/Analises/0/0_interactive_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/1.1_REDE_COMPLETA_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/1.2 - ALGUM RELACIONAMENTO (x2)/g' ~/SNArRDJF/Analises/0/x2_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/1.2_REDE_COMPLETA_ALGUM_RELACIONAMENTO_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/2_RELACIONAMENTO FORMAL (var0)/g' ~/SNArRDJF/Analises/0/var0_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/2_RELACIONAMENTO_FORMAL_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/3_REFERENCIA DE ENVIO (var1)/g' ~/SNArRDJF/Analises/0/var1_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/3_REFERENCIA_DE_ENVIO_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/4_REFERENCIA DE RECEBIMENTO CONTRAREFERENCIA (var2)/g' ~/SNArRDJF/Analises/0/var2_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/4_REFERENCIA_DE_RECEBIMENTO_CONTRAREFERENCIA_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/5_COORDENAÇÃO CONJUNTA DE CASOS (var3)/g' ~/SNArRDJF/Analises/0/var3_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/5_COORDENAÇÃO_CONJUNTA_DE_CASOS_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/6_PROGRAMAS EM CONJUNTO (var4)/g' ~/SNArRDJF/Analises/0/var4_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/6_PROGRAMAS_EM_CONJUNTO_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/7_OFERTA DE TREINAMENTOS CAPACITAÇÕES (var5)/g' ~/SNArRDJF/Analises/0/var5_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/7_OFERTA_DE_TREINAMENTOS_CAPACITAÇÕES_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/8_RECEBER TREINAMENTOS CAPACITAÇÕES (var6)/g' ~/SNArRDJF/Analises/0/var6_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/8_RECEBER_TREINAMENTOS_CAPACITAÇÕES_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/9_ACESSO A) Este serviço mostra-se disponível para realização de ativades em conjunto. (var7)/g' ~/SNArRDJF/Analises/0/var7_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/9_ACESSO_A_realização_de_ativades_em_conjunto_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/10_ACESSO B) O horário de funcionamento deste serviço possibilita a realização de ações em conjunto. (var8)/g' ~/SNArRDJF/Analises/0/var8_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/10_ACESSO_B_realização_de_ações_em_conjunto_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/11_ACESSO C) Este serviço disponibiliza informações sobre suas ativades para o seu serviço. (var9)/g' ~/SNArRDJF/Analises/0/var9_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/11_ACESSO_C_disponibiliza_informações_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/12_ACESSO D) O seu serviço consegue acessar facilmente informações deste serviço. (var10)/g' ~/SNArRDJF/Analises/0/var10_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/12_ACESSO_D_acessar_facilmente_informações_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/13_ACESSO E) Os canais de comunicação com este serviço são suficientes para realização de ações em conjunto. (var11)/g' ~/SNArRDJF/Analises/0/var11_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/13_ACESSO_E_canais_de_comunicação_suficientes_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/14_ACESSO F) Seu serviço tem facilade de entrar em contato com este serviço para realizar ativades em conjunto (var12)./g' ~/SNArRDJF/Analises/0/var12_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/14_ACESSO_F_entrar_em_contato_ara_realizar_ativades_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/15_ACESSO G) O acesso geográfico a este serviço impede a realização de ativades em conjunto. (var13) /g' ~/SNArRDJF/Analises/0/var13_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/15_ACESSO_G_O_acesso_geográfico_impede_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/16_ACESSO H) O custo para acessar este serviço impede a realização de ativades em conjunto. (var14)/g' ~/SNArRDJF/Analises/0/var14_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/16_ACESSO_H_O_custo_para_acessar_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/17_ACESSO I) O tempo gasto para acessar este serviço impede a realização ativades em conjunto. (var15)/g' ~/SNArRDJF/Analises/0/var15_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/17_ACESSO_I_O_tempo_gasto_para_acessar_este_serviço_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/18_CONFIANÇA A) Confia na qualificação profissional da equipe deste serviço.(var16)/g' ~/SNArRDJF/Analises/0/var16_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/18_CONFIANÇA_A_Confia_na_qualificação_profissional_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/19_CONFIANÇA B) Confia na capacade técnica da equipe deste serviço. (var17)/g' ~/SNArRDJF/Analises/0/var17_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/19_CONFIANÇA_B_Confia_na_capacade_técnica_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/20_CONFIANÇA C) Confia nas ações realizadas por este serviço. (var18)/g' ~/SNArRDJF/Analises/0/var18_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/20_CONFIANÇA_C_Confia_nas_ações_realizadas_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/21_CONFIANÇA D) Confia em compartilhar informações internas com este serviço. (var19) /g' ~/SNArRDJF/Analises/0/var19_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/21_CONFIANÇA_D_Confia_em_compartilhar_informações_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/22_CONFIANÇA E) Confia nas informações recebas deste serviço (var20)./g' ~/SNArRDJF/Analises/0/var20_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/22_CONFIANÇA_E_Confia_nas_informações_recebidas_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/23_CONFIANÇA F) Confia em realizar ações conjuntas com este serviço (var21)./g' ~/SNArRDJF/Analises/0/var21_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/23_CONFIANÇA_F_Confia_em_realizar_ações_conjuntas_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/24_CONFIANÇA G) Está satisfeito com as ações desempenhadas por este serviço (var22)./g' ~/SNArRDJF/Analises/0/var22_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/24_CONFIANÇA_G_Está_satisfeito_com_as_ações_desempenhadas_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/25_CONFIANÇA H) Espera que o relacionamento com este serviço continue nos próximos anos (var23)./g' ~/SNArRDJF/Analises/0/var23_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/25_CONFIANÇA_H_Relacionamento_continue_nos_próximos_anos_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/26_CONFIANÇA I) Espera que o relacionamento com este serviço se fortaleça nos próximos anos. (var24)/g' ~/SNArRDJF/Analises/0/var24_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/26_CONFIANÇA_I_Relacionamento_se_fortaleça_nos_próximos_anos_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/27_ATIVIDADE/g' ~/SNArRDJF/Analises/0/atividade_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/27_ATIVIDADE_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/28_ACESSO/g' ~/SNArRDJF/Analises/0/acesso_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/28_ACESSO_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/29_ACESSO_POSITIVO/g' ~/SNArRDJF/Analises/0/acesso_positivo_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/29_ACESSO_POSITIVO_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/30_ACESSO_NEGATIVO/g' ~/SNArRDJF/Analises/0/acesso_negativo_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/30_ACESSO_NEGATIVO_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/31_CONFIANÇA/g' ~/SNArRDJF/Analises/0/confianca_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/31_CONFIANÇA_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/32_ACESSO E CONFIANÇA/g' ~/SNArRDJF/Analises/0/acessoeconfianca_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/32_ACESSO_E_CONFIANÇA_0_interactive.Rmd" %>% system()

x<-"sed -e 's/fuull_no_zero_fancy/33_TOTAL/g' ~/SNArRDJF/Analises/0/total_0_interactive.Rmd >  ~/SNArRDJF/Analises/0/Scripts_Finais/33_TOTAL_0_interactive.Rmd" %>% system()
```

```{r}
render("~/SNArRDJF/Analises/0/Scripts_Finais/1.1_REDE_COMPLETA_0_interactive.Rmd","all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/1.2_REDE_COMPLETA_ALGUM_RELACIONAMENTO_0_interactive.Rmd","all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/2_RELACIONAMENTO_FORMAL_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/3_REFERENCIA_DE_ENVIO_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/4_REFERENCIA_DE_RECEBIMENTO_CONTRAREFERENCIA_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/5_COORDENAÇÃO_CONJUNTA_DE_CASOS_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/6_PROGRAMAS_EM_CONJUNTO_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/7_OFERTA_DE_TREINAMENTOS_CAPACITAÇÕES_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/8_RECEBER_TREINAMENTOS_CAPACITAÇÕES_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/9_ACESSO_A_realização_de_ativades_em_conjunto_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/10_ACESSO_B_realização_de_ações_em_conjunto_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/11_ACESSO_C_disponibiliza_informações_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/12_ACESSO_D_acessar_facilmente_informações_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/13_ACESSO_E_canais_de_comunicação_suficientes_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/14_ACESSO_F_entrar_em_contato_ara_realizar_ativades_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/15_ACESSO_G_O_acesso_geográfico_impede_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/16_ACESSO_H_O_custo_para_acessar_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/17_ACESSO_I_O_tempo_gasto_para_acessar_este_serviço_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/18_CONFIANÇA_A_Confia_na_qualificação_profissional_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/19_CONFIANÇA_B_Confia_na_capacade_técnica_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/20_CONFIANÇA_C_Confia_nas_ações_realizadas_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/21_CONFIANÇA_D_Confia_em_compartilhar_informações_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/22_CONFIANÇA_E_Confia_nas_informações_recebidas_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/23_CONFIANÇA_F_Confia_em_realizar_ações_conjuntas_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/24_CONFIANÇA_G_Está_satisfeito_com_as_ações_desempenhadas_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/25_CONFIANÇA_H_Relacionamento_continue_nos_próximos_anos_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/26_CONFIANÇA_I_Relacionamento_se_fortaleça_nos_próximos_anos_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/27_ATIVIDADE_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/28_ACESSO_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/29_ACESSO_POSITIVO_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/30_ACESSO_NEGATIVO_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/31_CONFIANÇA_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/32_ACESSO_E_CONFIANÇA_0_interactive.Rmd" ,"all")

render("~/SNArRDJF/Analises/0/Scripts_Finais/33_TOTAL_0_interactive.Rmd" ,"all")
```

```{r}
save.image("~/SNArRDJF/Analises/0/6.Cathemall.RData")
```

